name: Django Pre-Commit

on:
  push:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Reformat with black
      run: |
        black --check --exclude '/todo/todo/' .
    - name: Unit Tests and Coverage Report
      run: |
        coverage run --source=api manage.py test api.tests_unit
        coverage report
    - name: Integration Tests and Coverage Report
      run: |
        coverage run --source=api manage.py test api.tests_integration
        coverage report